### ISSUE TITLE
Tomatoes from the supermarket are immature

### ISSUE THREAD

**Issue by HybridDog** [gdiggs/lasagna#2]
Tomatoes from the market taste bad (in my opinion), l often don't like to eat them, whereas ripe tomatoes harvested in the garden taste great, l like eating them bare.
As far as l know, the raw tomatoes sold at supermarkets are maturated for increased keepability, only the can tomatoes and tomato sauces are made of ripe ones.
So l think you should cook your own sauce only if you cultivate your own tomatoes.

**Comment by gdiggs** [comment]
@HybridDog I agree with you - no store-bought tomatoes as good as home-grown ones. That being said, my recipe currently uses canned tomatoes, and in my experience those work better than any fresh tomatoes, store-bought or home-grown.
